[WIP] Update cache guide to including the caching for traced models
huggingface/optimum-neuron pull request #557
Opened 2024-04-08 16:08 UTC by JingyaHuang

# What does this PR do?

Add doc

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

2024-04-08 16:11 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/optimum-neuron/pr_557). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-04-15 07:19 UTC, dacorvo requested changes

2024-04-15 07:19 UTC, dacorvo commented on docs/source/guides/cache_system.mdx
> +- 1st approach: convert it to a set of [XLA](https://github.com/pytorch/xla/) subgraphs, and compile each subgraph with the neuronx compiler into a Neuron Executable File Format (NEFF) binary file(eg
```suggestion
- 1st approach: convert it to a set of [XLA](https://github.com/pytorch/xla/) subgraphs, and compile each subgraph with the neuronx compiler into a Neuron Executable File Format (NEFF) binary file (eg. training and inference of llm). 
```

2024-04-15 07:19 UTC, dacorvo commented on docs/source/guides/cache_system.mdx
> +- 2nd approach: recorde one graph, compile it with the neuronx-cc compiler to a NEFF binary file, and serialize as a TorchScript module(eg. inference of encoders, stable diffusion and seq2seq models)
```suggestion
- 2nd approach: record one graph, compile it with the neuronx-cc compiler to a NEFF binary file, and serialize as a TorchScript module (eg. inference of encoders, stable diffusion and seq2seq models).
```

2024-04-15 07:19 UTC, dacorvo commented on docs/source/guides/cache_system.mdx
> + stores NEFF files in a local directory, usually `/var/tmp/neuron-compile-cache`. And for models adopting the second approach, the compiled Neuron models with checkpoint artiifacts (eg. config, token
```suggestion
 stores NEFF files in a local directory, usually `/var/tmp/neuron-compile-cache`. And for models adopting the second approach, the compiled Neuron models with checkpoint artifacts (eg. config, tokenizer) will be stored by Optimum Neuron after the the first time compilation as well.
```

2024-04-15 07:19 UTC, dacorvo commented on docs/source/guides/cache_system.mdx
> +It is important to understand that the cache of training / models applying `transformers_neuronx`operates on NEFF binaries, and not on the model itself.
```suggestion
It is important to understand that the cache of training / models applying `transformers_neuronx` operates on NEFF binaries, and not on the model itself.
```

2024-04-15 09:21 UTC, michaelbenayoun commented on docs/source/guides/cache_system.mdx
> +- 2nd approach: recorde one graph, compile it with the neuronx-cc compiler to a NEFF binary file, and serialize as a TorchScript module(eg. inference of encoders, stable diffusion and seq2seq models)
```suggestion
- 2nd approach: recorde one graph via tracing (TorchScript), compile it with the neuronx compiler to a NEFF binary file, and serialize as a TorchScript module(eg. inference of encoders, stable diffusion and seq2seq models).
```
Between the two bullet points you use "neuronx compiler" and "neuronx-cc compiler". I think the former is more accurate.

2024-04-15 09:21 UTC, michaelbenayoun commented on docs/source/guides/cache_system.mdx
> + stores NEFF files in a local directory, usually `/var/tmp/neuron-compile-cache`. And for models adopting the second approach, the compiled Neuron models with checkpoint artiifacts (eg. config, token
```suggestion
 stores NEFF files in a local directory, usually `/var/tmp/neuron-compile-cache`. And for models adopting the second approach, the compiled Neuron models with checkpoint artiifacts (eg. config, tokenizer) will be stored by `optimum-neuron` after the the first time compilation as well.
```

2024-04-15 09:21 UTC, michaelbenayoun commented on docs/source/guides/cache_system.mdx
> +It is important to understand that the cache of training / models applying `transformers_neuronx`operates on NEFF binaries, and not on the model itself.
I dont really understand this sentence. Especially the "training / models" part
```suggestion
It is important to understand that the cache of training / models applying `transformers_neuronx`operates on NEFF binaries, and not on the model itself.
```

2024-05-12 08:04 UTC, HuggingFaceDocBuilderDev commented
This issue has been automatically marked as stale because it has not had recent activity. If you think this still needs to be addressed please comment on this thread. Thank you!

2024-06-06 08:04 UTC, HuggingFaceDocBuilderDev commented
This issue has been automatically marked as stale because it has not had recent activity. If you think this still needs to be addressed please comment on this thread. Thank you!

2024-06-06 08:35 UTC, michaelbenayoun commented
What's the status on that? @JingyaHuang do you need our reviews?

2024-06-06 08:46 UTC, JingyaHuang commented
@michaelbenayoun I will need to update it a bit since there are some changes. Will ask for another review once done!

2024-07-01 08:05 UTC, HuggingFaceDocBuilderDev commented
This issue has been automatically marked as stale because it has not had recent activity. If you think this still needs to be addressed please comment on this thread. Thank you!

2024-07-01 09:00 UTC, michaelbenayoun approved these changes

2024-07-26 08:04 UTC, HuggingFaceDocBuilderDev commented
This issue has been automatically marked as stale because it has not had recent activity. If you think this still needs to be addressed please comment on this thread. Thank you!

2024-08-19 08:05 UTC, HuggingFaceDocBuilderDev commented
This issue has been automatically marked as stale because it has not had recent activity. If you think this still needs to be addressed please comment on this thread. Thank you!

2024-09-13 08:05 UTC, HuggingFaceDocBuilderDev commented
This issue has been automatically marked as stale because it has not had recent activity. If you think this still needs to be addressed please comment on this thread. Thank you!

2024-10-07 08:05 UTC, HuggingFaceDocBuilderDev commented
This issue has been automatically marked as stale because it has not had recent activity. If you think this still needs to be addressed please comment on this thread. Thank you!

2024-10-28 08:05 UTC, closed without merging